<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Country Report - {{ $country->name }} - {{ now()->format('M d, Y') }}</title>
    <style>
        @page {
            size: A4 portrait;
            margin: 15mm;
        }

        body {
            font-family: Arial, sans-serif;
            font-size: 10px;
            margin: 0;
            padding: 0;
            background-color: #fff;
            color: #000;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #000;
        }

        .header h1 {
            font-size: 20px;
            margin: 5px 0;
            font-weight: bold;
            text-transform: uppercase;
        }

        .header p {
            margin: 3px 0;
            font-size: 9px;
            color: #666;
        }

        .section-title {
            font-size: 14px;
            font-weight: bold;
            margin: 15px 0 8px 0;
            padding-bottom: 5px;
            border-bottom: 2px solid #000;
            text-transform: uppercase;
        }

        .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
            margin-bottom: 15px;
        }

        .stat-box {
            border: 1px solid #000;
            padding: 8px;
            text-align: center;
        }

        .stat-box .label {
            font-size: 8px;
            color: #666;
            text-transform: uppercase;
            font-weight: bold;
            margin-bottom: 3px;
        }

        .stat-box .value {
            font-size: 16px;
            font-weight: bold;
            color: #000;
        }

        .stat-box .subtext {
            font-size: 7px;
            color: #666;
            margin-top: 2px;
        }

        .detail-table {
            width: 100%;
            margin-bottom: 15px;
        }

        .detail-table th,
        .detail-table td {
            border: 1px solid #000;
            padding: 6px;
            text-align: left;
        }

        .detail-table th {
            background-color: #f2f2f2;
            font-weight: bold;
            font-size: 9px;
            text-transform: uppercase;
        }

        .detail-table td {
            font-size: 9px;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .footer {
            text-align: center;
            font-size: 8px;
            color: #666;
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #ddd;
            page-break-inside: avoid;
        }

        .two-column {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
            margin-bottom: 15px;
        }

        .status-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 5px;
            margin-bottom: 10px;
        }

        .status-item {
            border: 1px solid #ddd;
            padding: 5px;
            text-align: center;
            font-size: 9px;
        }

        .status-item .status-label {
            font-weight: bold;
            color: #666;
        }

        .status-item .status-value {
            font-size: 14px;
            font-weight: bold;
            margin-top: 2px;
        }

        @media print {
            body {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>Comprehensive Country Report</h1>
        <h2 style="font-size: 16px; margin: 5px 0;">{{ strtoupper($country->name) }}</h2>
        <p>Report Period: {{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} - {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}</p>
        <p>Generated By: {{ auth()->user()->name }} ({{ auth()->user()->email }})</p>
        <p>Generated On: {{ now()->format('d/m/Y H:i:s') }}</p>
    </div>

    <!-- Executive Summary -->
    <div class="section-title">Executive Summary</div>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="label">Total Vendors</div>
            <div class="value">{{ number_format($vendorsStats['total']) }}</div>
            <div class="subtext">{{ $vendorsStats['verified'] }} Verified</div>
        </div>
        <div class="stat-box">
            <div class="label">Total Products</div>
            <div class="value">{{ number_format($productsStats['total']) }}</div>
            <div class="subtext">{{ number_format($productsStats['total_views']) }} Views</div>
        </div>
        <div class="stat-box">
            <div class="label">Total Orders</div>
            <div class="value">{{ number_format($ordersStats['total']) }}</div>
            <div class="subtext">${{ number_format($ordersStats['total_value'], 2) }}</div>
        </div>
        <div class="stat-box">
            <div class="label">Transporters</div>
            <div class="value">{{ number_format($transportersStats['total']) }}</div>
            <div class="subtext">{{ number_format($transportersStats['total_fleet']) }} Vehicles</div>
        </div>
    </div>

    <!-- Period Performance -->
    <div class="section-title">Period Performance</div>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="label">New Vendors</div>
            <div class="value">{{ number_format($vendorsStats['new_this_period']) }}</div>
        </div>
        <div class="stat-box">
            <div class="label">New Products</div>
            <div class="value">{{ number_format($productsStats['new_this_period']) }}</div>
        </div>
        <div class="stat-box">
            <div class="label">Orders</div>
            <div class="value">{{ number_format($ordersStats['period_orders']) }}</div>
        </div>
        <div class="stat-box">
            <div class="label">Revenue</div>
            <div class="value">${{ number_format($ordersStats['period_value'], 2) }}</div>
        </div>
    </div>

    <!-- Vendors Details -->
    <div class="section-title">Vendors Status Breakdown</div>
    <div class="status-grid">
        <div class="status-item">
            <div class="status-label">Verified</div>
            <div class="status-value">{{ number_format($vendorsStats['verified']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Pending</div>
            <div class="status-value">{{ number_format($vendorsStats['pending']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Rejected</div>
            <div class="status-value">{{ number_format($vendorsStats['rejected']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Active</div>
            <div class="status-value">{{ number_format($vendorsStats['active']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Inactive</div>
            <div class="status-value">{{ number_format($vendorsStats['inactive']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Suspended</div>
            <div class="status-value">{{ number_format($vendorsStats['suspended']) }}</div>
        </div>
    </div>

    <!-- Products Details -->
    <div class="section-title">Products Status Breakdown</div>
    <div class="status-grid">
        <div class="status-item">
            <div class="status-label">Approved</div>
            <div class="status-value">{{ number_format($productsStats['approved']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Pending</div>
            <div class="status-value">{{ number_format($productsStats['pending']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Active</div>
            <div class="status-value">{{ number_format($productsStats['active']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Inactive</div>
            <div class="status-value">{{ number_format($productsStats['inactive']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Total Views</div>
            <div class="status-value">{{ number_format($productsStats['total_views']) }}</div>
        </div>
    </div>

    <!-- Orders Details -->
    <div class="section-title">Orders Status Breakdown</div>
    <div class="status-grid">
        <div class="status-item">
            <div class="status-label">Pending</div>
            <div class="status-value">{{ number_format($ordersStats['pending']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Confirmed</div>
            <div class="status-value">{{ number_format($ordersStats['confirmed']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Processing</div>
            <div class="status-value">{{ number_format($ordersStats['processing']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Shipped</div>
            <div class="status-value">{{ number_format($ordersStats['shipped']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Delivered</div>
            <div class="status-value">{{ number_format($ordersStats['delivered']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Cancelled</div>
            <div class="status-value">{{ number_format($ordersStats['cancelled']) }}</div>
        </div>
    </div>

    <!-- Showrooms & Loads Overview -->
    <div class="section-title">Showrooms & Transportation Overview</div>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="label">Total Showrooms</div>
            <div class="value">{{ number_format($showroomsStats['total']) }}</div>
            <div class="subtext">{{ $showroomsStats['verified'] }} Verified</div>
        </div>
        <div class="stat-box">
            <div class="label">Featured</div>
            <div class="value">{{ number_format($showroomsStats['featured']) }}</div>
            <div class="subtext">{{ $showroomsStats['authorized_dealers'] }} Authorized</div>
        </div>
        <div class="stat-box">
            <div class="label">Showroom Views</div>
            <div class="value">{{ number_format($showroomsStats['total_views']) }}</div>
            <div class="subtext">{{ number_format($showroomsStats['total_inquiries']) }} Inquiries</div>
        </div>
        <div class="stat-box">
            <div class="label">Total Loads</div>
            <div class="value">{{ number_format($loadsStats['total']) }}</div>
            <div class="subtext">{{ number_format($loadsStats['delivered']) }} Delivered</div>
        </div>
    </div>

    <!-- Loads Status -->
    <div class="section-title">Loads Status Breakdown</div>
    <div class="status-grid">
        <div class="status-item">
            <div class="status-label">Posted</div>
            <div class="status-value">{{ number_format($loadsStats['posted']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Bidding</div>
            <div class="status-value">{{ number_format($loadsStats['bidding']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Assigned</div>
            <div class="status-value">{{ number_format($loadsStats['assigned']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">In Transit</div>
            <div class="status-value">{{ number_format($loadsStats['in_transit']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Delivered</div>
            <div class="status-value">{{ number_format($loadsStats['delivered']) }}</div>
        </div>
        <div class="status-item">
            <div class="status-label">Cancelled</div>
            <div class="status-value">{{ number_format($loadsStats['cancelled']) }}</div>
        </div>
    </div>

    <!-- Transportation Details -->
    <div class="section-title">Transportation Details</div>
    <div class="stats-grid">
        <div class="stat-box">
            <div class="label">Total Transporters</div>
            <div class="value">{{ number_format($transportersStats['total']) }}</div>
            <div class="subtext">{{ $transportersStats['verified'] }} Verified</div>
        </div>
        <div class="stat-box">
            <div class="label">Total Fleet</div>
            <div class="value">{{ number_format($transportersStats['total_fleet']) }}</div>
            <div class="subtext">Vehicles</div>
        </div>
        <div class="stat-box">
            <div class="label">Average Rating</div>
            <div class="value">{{ number_format($transportersStats['average_rating'], 1) }}</div>
            <div class="subtext">Out of 5.0</div>
        </div>
        <div class="stat-box">
            <div class="label">Total Deliveries</div>
            <div class="value">{{ number_format($transportersStats['total_deliveries']) }}</div>
            <div class="subtext">All Time</div>
        </div>
    </div>

    <!-- Top Vendors -->
    @if($topVendors->count() > 0)
    <div class="section-title">Top 10 Vendors by Revenue (Period)</div>
    <table class="detail-table">
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 30%;">Vendor Name</th>
                <th style="width: 35%;">Business Name</th>
                <th style="width: 15%;" class="text-right">Orders</th>
                <th style="width: 15%;" class="text-right">Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($topVendors as $index => $vendor)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $vendor->name }}</td>
                <td>{{ $vendor->business_name }}</td>
                <td class="text-right">{{ number_format($vendor->total_orders) }}</td>
                <td class="text-right"><strong>${{ number_format($vendor->total_revenue, 2) }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- Top Products -->
    @if($topProducts->count() > 0)
    <div class="section-title">Top 10 Products by Views</div>
    <table class="detail-table">
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 50%;">Product Name</th>
                <th style="width: 30%;">Category</th>
                <th style="width: 15%;" class="text-right">Views</th>
            </tr>
        </thead>
        <tbody>
            @foreach($topProducts as $index => $product)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->category }}</td>
                <td class="text-right"><strong>{{ number_format($product->views) }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- Monthly Trends -->
    @if($monthlyOrders->count() > 0)
    <div class="section-title">Monthly Trends (Last 6 Months)</div>
    <table class="detail-table">
        <thead>
            <tr>
                <th style="width: 40%;">Month</th>
                <th style="width: 30%;" class="text-right">Orders</th>
                <th style="width: 30%;" class="text-right">Revenue</th>
            </tr>
        </thead>
        <tbody>
            @foreach($monthlyOrders as $monthly)
            <tr>
                <td>{{ \Carbon\Carbon::parse($monthly->month . '-01')->format('F Y') }}</td>
                <td class="text-right">{{ number_format($monthly->count) }}</td>
                <td class="text-right"><strong>${{ number_format($monthly->revenue, 2) }}</strong></td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <!-- Report Summary -->
    <div class="section-title">Report Summary</div>
    <table class="detail-table">
        <tbody>
            <tr>
                <td style="width: 30%; font-weight: bold;">Country</td>
                <td>{{ $country->name }} ({{ $country->code }})</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Report Period</td>
                <td>{{ \Carbon\Carbon::parse($startDate)->format('M d, Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('M d, Y') }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Total Orders Value</td>
                <td><strong>${{ number_format($ordersStats['total_value'], 2) }}</strong></td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Average Order Value</td>
                <td>${{ number_format($ordersStats['average_order_value'] ?? 0, 2) }}</td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Period Revenue</td>
                <td><strong>${{ number_format($ordersStats['period_value'], 2) }}</strong></td>
            </tr>
            <tr>
                <td style="font-weight: bold;">Total Weight Transported</td>
                <td>{{ number_format($loadsStats['total_weight'], 2) }} kg</td>
            </tr>
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p><strong>Country Admin Comprehensive Report</strong></p>
        <p>Report ID: RPT-{{ now()->format('Ymd-His') }} | Country: {{ $country->name }} | Generated: {{ now()->format('d/m/Y H:i:s') }}</p>
        <p>This report is confidential and intended for internal use only.</p>
    </div>

    <script>
        window.onload = function() {
            window.print();
        };
    </script>
</body>
</html>
