<?php

return [
    // Marketplace / Vendor
    'can_export'                       => ['label' => 'Can Export',                      'type' => 'boolean'],
    'can_has_ads'                      => ['label' => 'Can Have Ads',                    'type' => 'boolean'],
    'allowed_ads'                      => ['label' => 'Allowed Ads (count)',              'type' => 'number'],
    'can_recruit_sub_agents'           => ['label' => 'Recruit Sub-Agents',              'type' => 'boolean'],
    'can_request_exclusive_region'     => ['label' => 'Request Exclusive Region',        'type' => 'boolean'],
    'can_subscribe_tools'              => ['label' => 'Subscribe Tools',                 'type' => 'boolean'],
    'can_use_premium_tools'            => ['label' => 'Use Premium Tools',               'type' => 'boolean'],
    'commission_assigned_stores'       => ['label' => 'Commission — Assigned Stores %',  'type' => 'number'],
    'commission_own_stores'            => ['label' => 'Commission — Own Stores %',       'type' => 'number'],
    'email_campaigns_per_month'        => ['label' => 'Email Campaigns Per Month',       'type' => 'number'],
    'has_account_manager'              => ['label' => 'Account Manager',                 'type' => 'boolean'],
    'has_advanced_analytics'           => ['label' => 'Advanced Analytics',              'type' => 'boolean'],
    'has_advanced_automation'          => ['label' => 'Advanced Automation',             'type' => 'boolean'],
    'has_advanced_conversion_tracking' => ['label' => 'Advanced Conversion Tracking',   'type' => 'boolean'],
    'has_advanced_seo'                 => ['label' => 'Advanced SEO',                   'type' => 'boolean'],
    'has_ads'                          => ['label' => 'Ads',                             'type' => 'boolean'],
    'has_affiliate_marketing'          => ['label' => 'Affiliate Marketing',             'type' => 'boolean'],
    'has_affiliate_payout_system'      => ['label' => 'Affiliate Payout System',        'type' => 'boolean'],
    'has_agent_dashboard'              => ['label' => 'Agent Dashboard',                 'type' => 'boolean'],
    'has_agent_marketing_system'       => ['label' => 'Agent Marketing System',         'type' => 'boolean'],
    'has_ai_ad_optimization'           => ['label' => 'AI Ad Optimization',             'type' => 'boolean'],
    'has_ai_chatbot'                   => ['label' => 'AI Chatbot',                      'type' => 'boolean'],
    'has_ai_content_generation'        => ['label' => 'AI Content Generation',          'type' => 'boolean'],
    'has_ai_powered_tools'             => ['label' => 'AI Powered Tools',               'type' => 'boolean'],
    'has_analytics'                    => ['label' => 'Analytics',                       'type' => 'boolean'],
    'has_api_access'                   => ['label' => 'API Access',                      'type' => 'boolean'],
    'has_api_integration'              => ['label' => 'API Integration',                 'type' => 'boolean'],
    'has_b2b_marketplace_promotion'    => ['label' => 'B2B Marketplace Promotion',      'type' => 'boolean'],
    'has_b2b_marketing'                => ['label' => 'B2B Marketing',                   'type' => 'boolean'],
    'has_basic_analytics'              => ['label' => 'Basic Analytics',                 'type' => 'boolean'],
    'has_basic_crm'                    => ['label' => 'Basic CRM',                       'type' => 'boolean'],
    'has_basic_graphics_design'        => ['label' => 'Basic Graphics Design',          'type' => 'boolean'],
    'has_basic_search_visibility'      => ['label' => 'Basic Search Visibility',        'type' => 'boolean'],
    'has_basic_seo'                    => ['label' => 'Basic SEO',                       'type' => 'boolean'],
    'has_basic_stats'                  => ['label' => 'Basic Stats',                     'type' => 'boolean'],
    'has_basic_website'                => ['label' => 'Basic Website',                   'type' => 'boolean'],
    'has_brand_domination'             => ['label' => 'Brand Domination',               'type' => 'boolean'],
    'has_brand_positioning'            => ['label' => 'Brand Positioning',              'type' => 'boolean'],
    'has_brand_profile_setup'          => ['label' => 'Brand Profile Setup',            'type' => 'boolean'],
    'has_brand_strategy'               => ['label' => 'Brand Strategy',                 'type' => 'boolean'],
    'has_brand_storytelling'           => ['label' => 'Brand Storytelling',             'type' => 'boolean'],
    'has_business_listing'             => ['label' => 'Business Listing',               'type' => 'boolean'],
    'has_buyer_messaging'              => ['label' => 'Buyer Messaging',                 'type' => 'boolean'],
    'has_client_sub_accounts'          => ['label' => 'Client Sub Accounts',            'type' => 'boolean'],
    'has_commission_wallet'            => ['label' => 'Commission Wallet',              'type' => 'boolean'],
    'has_company_page'                 => ['label' => 'Company Page',                    'type' => 'boolean'],
    'has_country_targeting'            => ['label' => 'Country Targeting',              'type' => 'boolean'],
    'has_country_visibility'           => ['label' => 'Country Visibility',             'type' => 'boolean'],
    'has_crm'                          => ['label' => 'CRM',                             'type' => 'boolean'],
    'has_custom_integrations'          => ['label' => 'Custom Integrations',            'type' => 'boolean'],
    'has_custom_onboarding_tools'      => ['label' => 'Custom Onboarding Tools',        'type' => 'boolean'],
    'has_custom_software_integrations' => ['label' => 'Custom Software Integrations',  'type' => 'boolean'],
    'has_dedicated_manager'            => ['label' => 'Dedicated Manager',              'type' => 'boolean'],
    'has_dedicated_support'            => ['label' => 'Dedicated Support',              'type' => 'boolean'],
    'has_display_ads'                  => ['label' => 'Display Ads',                    'type' => 'boolean'],
    'has_documentaries'                => ['label' => 'Documentaries',                  'type' => 'boolean'],
    'has_drip_campaigns'               => ['label' => 'Drip Campaigns',                 'type' => 'boolean'],
    'has_ecommerce_store'              => ['label' => 'E-Commerce Store',               'type' => 'boolean'],
    'has_email_alerts'                 => ['label' => 'Email Alerts',                   'type' => 'boolean'],
    'has_email_automation'             => ['label' => 'Email Automation',               'type' => 'boolean'],
    'has_email_marketing'              => ['label' => 'Email Marketing',                'type' => 'boolean'],
    'has_email_marketing_access'       => ['label' => 'Email Marketing Access',         'type' => 'boolean'],
    'has_email_notifications'          => ['label' => 'Email Notifications',            'type' => 'boolean'],
    'has_enterprise_sla'               => ['label' => 'Enterprise SLA',                 'type' => 'boolean'],
    'has_facebook'                     => ['label' => 'Facebook',                        'type' => 'boolean'],
    'has_facebook_ads'                 => ['label' => 'Facebook Ads',                   'type' => 'boolean'],
    'has_full_store_dashboard'         => ['label' => 'Full Store Dashboard',           'type' => 'boolean'],
    'has_global_influencers'           => ['label' => 'Global Influencers',             'type' => 'boolean'],
    'has_global_marketplace'           => ['label' => 'Global Marketplace',             'type' => 'boolean'],
    'has_google_business_profile'      => ['label' => 'Google Business Profile',        'type' => 'boolean'],
    'has_google_display_ads'           => ['label' => 'Google Display Ads',             'type' => 'boolean'],
    'has_google_search_ads'            => ['label' => 'Google Search Ads',              'type' => 'boolean'],
    'has_homepage_exposure'            => ['label' => 'Homepage Exposure',              'type' => 'boolean'],
    'has_influencer_marketing'         => ['label' => 'Influencer Marketing',           'type' => 'boolean'],
    'has_influencer_payout_system'     => ['label' => 'Influencer Payout System',      'type' => 'boolean'],
    'has_instagram'                    => ['label' => 'Instagram',                       'type' => 'boolean'],
    'has_instagram_ads'                => ['label' => 'Instagram Ads',                  'type' => 'boolean'],
    'has_international_seo'            => ['label' => 'International SEO',              'type' => 'boolean'],
    'has_international_targeting'      => ['label' => 'International Targeting',        'type' => 'boolean'],
    'has_landing_page'                 => ['label' => 'Landing Page',                   'type' => 'boolean'],
    'has_lead_distribution'            => ['label' => 'Lead Distribution',              'type' => 'boolean'],
    'has_lead_qualification'           => ['label' => 'Lead Qualification',             'type' => 'boolean'],
    'has_lead_tracking'                => ['label' => 'Lead Tracking',                  'type' => 'boolean'],
    'has_linkedin'                     => ['label' => 'LinkedIn',                        'type' => 'boolean'],
    'has_linkedin_b2b_ads'             => ['label' => 'LinkedIn B2B Ads',               'type' => 'boolean'],
    'has_live_selling'                 => ['label' => 'Live Selling',                   'type' => 'boolean'],
    'has_live_streaming'               => ['label' => 'Live Streaming',                 'type' => 'boolean'],
    'has_livestream'                   => ['label' => 'Livestream',                      'type' => 'boolean'],
    'has_livestream_discount'          => ['label' => 'Livestream Discount',            'type' => 'boolean'],
    'has_livestream_tools'             => ['label' => 'Livestream Tools',               'type' => 'boolean'],
    'has_local_branding'               => ['label' => 'Local Branding',                 'type' => 'boolean'],
    'has_marketing_automation'         => ['label' => 'Marketing Automation',           'type' => 'boolean'],
    'has_marketplace_tools_demo'       => ['label' => 'Marketplace Tools Demo',         'type' => 'boolean'],
    'has_media_coverage'               => ['label' => 'Media Coverage',                 'type' => 'boolean'],
    'has_monthly_reports'              => ['label' => 'Monthly Reports',                'type' => 'boolean'],
    'has_multi_country_campaigns'      => ['label' => 'Multi-Country Campaigns',        'type' => 'boolean'],
    'has_multi_language'               => ['label' => 'Multi Language',                 'type' => 'boolean'],
    'has_multi_page_website'           => ['label' => 'Multi-Page Website',             'type' => 'boolean'],
    'has_multi_region_dashboard'       => ['label' => 'Multi Region Dashboard',         'type' => 'boolean'],
    'has_multilanguage_listings'       => ['label' => 'Multilanguage Listings',         'type' => 'boolean'],
    'has_national_sponsored_ads'       => ['label' => 'National Sponsored Ads',         'type' => 'boolean'],
    'has_paid_ads'                     => ['label' => 'Paid Ads',                        'type' => 'boolean'],
    'has_performance_reports'          => ['label' => 'Performance Reports',            'type' => 'boolean'],
    'has_pr_services'                  => ['label' => 'PR Services',                    'type' => 'boolean'],
    'has_press_releases'               => ['label' => 'Press Releases',                 'type' => 'boolean'],
    'has_priority_ranking'             => ['label' => 'Priority Ranking',               'type' => 'boolean'],
    'has_product_seo_optimization'     => ['label' => 'Product SEO Optimization',      'type' => 'boolean'],
    'has_programmatic_ads'             => ['label' => 'Programmatic Ads',               'type' => 'boolean'],
    'has_promotions'                   => ['label' => 'Promotions',                      'type' => 'boolean'],
    'has_reels'                        => ['label' => 'Reels',                           'type' => 'boolean'],
    'has_referral_link_system'         => ['label' => 'Referral Link System',           'type' => 'boolean'],
    'has_regional_analytics'           => ['label' => 'Regional Analytics',             'type' => 'boolean'],
    'has_regional_campaigns'           => ['label' => 'Regional Campaigns',             'type' => 'boolean'],
    'has_regional_influencers'         => ['label' => 'Regional Influencers',           'type' => 'boolean'],
    'has_regional_visibility'          => ['label' => 'Regional Visibility',            'type' => 'boolean'],
    'has_reputation_management'        => ['label' => 'Reputation Management',          'type' => 'boolean'],
    'has_retargeting_ads'              => ['label' => 'Retargeting Ads',                'type' => 'boolean'],
    'has_rfq_access'                   => ['label' => 'RFQ Access',                     'type' => 'boolean'],
    'has_rfq_lead_generation'          => ['label' => 'RFQ Lead Generation',            'type' => 'boolean'],
    'has_rfq_management'               => ['label' => 'RFQ Management',                 'type' => 'boolean'],
    'has_roi_dashboards'               => ['label' => 'ROI Dashboards',                 'type' => 'boolean'],
    'has_short_videos'                 => ['label' => 'Short Videos',                   'type' => 'boolean'],
    'has_sms_marketing'                => ['label' => 'SMS Marketing',                  'type' => 'boolean'],
    'has_social_media'                 => ['label' => 'Social Media',                   'type' => 'boolean'],
    'has_social_media_setup'           => ['label' => 'Social Media Setup',             'type' => 'boolean'],
    'has_sponsored_ads_credits'        => ['label' => 'Sponsored Ads Credits',          'type' => 'boolean'],
    'has_sponsored_supplier_listings'  => ['label' => 'Sponsored Supplier Listings',   'type' => 'boolean'],
    'has_store_performance_tracking'   => ['label' => 'Store Performance Tracking',    'type' => 'boolean'],
    'has_sub_agent_management'         => ['label' => 'Sub-Agent Management',           'type' => 'boolean'],
    'has_tiktok'                       => ['label' => 'TikTok',                          'type' => 'boolean'],
    'has_tiktok_ads'                   => ['label' => 'TikTok Ads',                     'type' => 'boolean'],
    'has_tiktok_content'               => ['label' => 'TikTok Content',                 'type' => 'boolean'],
    'has_trust_score_boost'            => ['label' => 'Trust Score Boost',              'type' => 'boolean'],
    'has_unlimited_campaigns'          => ['label' => 'Unlimited Campaigns',            'type' => 'boolean'],
    'has_verified_badge'               => ['label' => 'Verified Badge',                 'type' => 'boolean'],
    'has_video_ads'                    => ['label' => 'Video Ads',                      'type' => 'boolean'],
    'has_video_content'                => ['label' => 'Video Content',                  'type' => 'boolean'],
    'has_weekly_analytics'             => ['label' => 'Weekly Analytics',               'type' => 'boolean'],
    'has_whatsapp_business_setup'      => ['label' => 'WhatsApp Business Setup',        'type' => 'boolean'],
    'has_whatsapp_campaigns'           => ['label' => 'WhatsApp Campaigns',             'type' => 'boolean'],
    'has_whatsapp_notifications'       => ['label' => 'WhatsApp Notifications',         'type' => 'boolean'],
    'has_white_label'                  => ['label' => 'White Label',                    'type' => 'boolean'],
    'has_white_label_dashboard'        => ['label' => 'White Label Dashboard',          'type' => 'boolean'],
    'has_youtube'                      => ['label' => 'YouTube',                         'type' => 'boolean'],
    'has_youtube_optimization'         => ['label' => 'YouTube Optimization',           'type' => 'boolean'],
    'influencer_tier'                  => ['label' => 'Influencer Tier',                'type' => 'text'],
    'is_one_time_payment'              => ['label' => 'One-Time Payment',               'type' => 'boolean'],
    'max_campaigns'                    => ['label' => 'Max Campaigns',                  'type' => 'number_or_unlimited'],
    'max_messages'                     => ['label' => 'Max Messages',                   'type' => 'number_or_unlimited'],
    'max_product_catalog'              => ['label' => 'Max Product Catalog',            'type' => 'number'],
    'max_products'                     => ['label' => 'Max Products',                   'type' => 'number_or_unlimited'],
    'max_stores'                       => ['label' => 'Max Stores',                     'type' => 'number_or_unlimited'],
    'max_sub_accounts'                 => ['label' => 'Max Sub Accounts',               'type' => 'number_or_unlimited'],
    'monthly_sponsored_ad_slots'       => ['label' => 'Monthly Sponsored Ad Slots',     'type' => 'number'],
    'priority_ranking'                 => ['label' => 'Priority Ranking (value)',       'type' => 'number'],
    'social_posts_per_month'           => ['label' => 'Social Posts Per Month',         'type' => 'number_or_unlimited'],
    'sponsored_ads_discount'           => ['label' => 'Sponsored Ads Discount %',      'type' => 'number'],
    'sub_agent_override_commission'    => ['label' => 'Sub-Agent Override Commission %','type' => 'number'],
    'support_level'                    => ['label' => 'Support Level',                  'type' => 'text'],
    'supported_languages'              => ['label' => 'Supported Languages',            'type' => 'text'],
    'system_transaction_fee'           => ['label' => 'System Transaction Fee %',       'type' => 'number'],
    'tier_level'                       => ['label' => 'Tier Level',                     'type' => 'number'],
    'tier_name'                        => ['label' => 'Tier Name',                      'type' => 'text'],
    'yearly_savings'                   => ['label' => 'Yearly Savings',                 'type' => 'text'],
];
